# Generated by Django 5.0.14 on 2026-09-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='portfolio.portfoliouser')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(blank=True, max_length=300, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade_gpa', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='education', to='portfolio.profile')),
            ],
            options={
                'db_table': 'education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_value', models.CharField(blank=True, max_length=300, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='portfolio.profile')),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('certification_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('issuing_organization', models.CharField(blank=True, max_length=300, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=200, null=True)),
                ('credential_url', models.CharField(blank=True, max_length=500, null=True)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='portfolio.profile')),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('viewers_count', models.IntegerField(default=0)),
                ('visited_time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolio.profile')),
            ],
            options={
                'db_table': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_achieved', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='portfolio.profile')),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('about_me_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='about_entries', to='portfolio.profile')),
            ],
            options={
                'db_table': 'aboutme',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('github_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.profile')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['display_order', '-is_featured'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('project_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_url', models.CharField(blank=True, max_length=500, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.project')),
            ],
            options={
                'db_table': 'project_media',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('version_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='portfolio.profile')),
            ],
            options={
                'db_table': 'resume',
                'ordering': ['-is_primary', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('year_acquired', models.IntegerField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=300, null=True)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.profile')),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['category', 'name'],
            },
        ),
    ]
